countriesList.Add(new Country { label = "AD", description = "Andorra" });
countriesList.Add(new Country { label = "AE", description = "United Arab Emirates" });
countriesList.Add(new Country { label = "AF", description = "Afghanistan" });
countriesList.Add(new Country { label = "AG", description = "Antigua & Barbuda" });
countriesList.Add(new Country { label = "AI", description = "Anguilla" });
countriesList.Add(new Country { label = "AL", description = "Albania" });
countriesList.Add(new Country { label = "AM", description = "Armenia" });
countriesList.Add(new Country { label = "AO", description = "Angola" });
countriesList.Add(new Country { label = "AQ", description = "Antarctica" });
countriesList.Add(new Country { label = "AR", description = "Argentina" });
countriesList.Add(new Country { label = "AS", description = "Samoa (American)" });
countriesList.Add(new Country { label = "AT", description = "Austria" });
countriesList.Add(new Country { label = "AU", description = "Australia" });
countriesList.Add(new Country { label = "AW", description = "Aruba" });
countriesList.Add(new Country { label = "AX", description = "Aaland Islands" });
countriesList.Add(new Country { label = "AZ", description = "Azerbaijan" });
countriesList.Add(new Country { label = "BA", description = "Bosnia & Herzegovina" });
countriesList.Add(new Country { label = "BB", description = "Barbados" });
countriesList.Add(new Country { label = "BD", description = "Bangladesh" });
countriesList.Add(new Country { label = "BE", description = "Belgium" });
countriesList.Add(new Country { label = "BF", description = "Burkina Faso" });
countriesList.Add(new Country { label = "BG", description = "Bulgaria" });
countriesList.Add(new Country { label = "BH", description = "Bahrain" });
countriesList.Add(new Country { label = "BI", description = "Burundi" });
countriesList.Add(new Country { label = "BJ", description = "Benin" });
countriesList.Add(new Country { label = "BL", description = "St Barthelemy" });
countriesList.Add(new Country { label = "BM", description = "Bermuda" });
countriesList.Add(new Country { label = "BN", description = "Brunei" });
countriesList.Add(new Country { label = "BO", description = "Bolivia" });
countriesList.Add(new Country { label = "BQ", description = "Caribbean Netherlands" });
countriesList.Add(new Country { label = "BR", description = "Brazil" });
countriesList.Add(new Country { label = "BS", description = "Bahamas" });
countriesList.Add(new Country { label = "BT", description = "Bhutan" });
countriesList.Add(new Country { label = "BV", description = "Bouvet Island" });
countriesList.Add(new Country { label = "BW", description = "Botswana" });
countriesList.Add(new Country { label = "BY", description = "Belarus" });
countriesList.Add(new Country { label = "BZ", description = "Belize" });
countriesList.Add(new Country { label = "CA", description = "Canada" });
countriesList.Add(new Country { label = "CC", description = "Cocos (Keeling) Islands" });
countriesList.Add(new Country { label = "CD", description = "Congo (Dem. Rep.)" });
countriesList.Add(new Country { label = "CF", description = "Central African Rep." });
countriesList.Add(new Country { label = "CG", description = "Congo (Rep.)" });
countriesList.Add(new Country { label = "CH", description = "Switzerland" });
countriesList.Add(new Country { label = "CI", description = "Cote d'Ivoire" });
countriesList.Add(new Country { label = "CK", description = "Cook Islands" });
countriesList.Add(new Country { label = "CL", description = "Chile" });
countriesList.Add(new Country { label = "CM", description = "Cameroon" });
countriesList.Add(new Country { label = "CN", description = "China" });
countriesList.Add(new Country { label = "CO", description = "Colombia" });
countriesList.Add(new Country { label = "CR", description = "Costa Rica" });
countriesList.Add(new Country { label = "CU", description = "Cuba" });
countriesList.Add(new Country { label = "CV", description = "Cape Verde" });
countriesList.Add(new Country { label = "CW", description = "Curacao" });
countriesList.Add(new Country { label = "CX", description = "Christmas Island" });
countriesList.Add(new Country { label = "CY", description = "Cyprus" });
countriesList.Add(new Country { label = "CZ", description = "Czech Republic" });
countriesList.Add(new Country { label = "DE", description = "Germany" });
countriesList.Add(new Country { label = "DJ", description = "Djibouti" });
countriesList.Add(new Country { label = "DK", description = "Denmark" });
countriesList.Add(new Country { label = "DM", description = "Dominica" });
countriesList.Add(new Country { label = "DO", description = "Dominican Republic" });
countriesList.Add(new Country { label = "DZ", description = "Algeria" });
countriesList.Add(new Country { label = "EC", description = "Ecuador" });
countriesList.Add(new Country { label = "EE", description = "Estonia" });
countriesList.Add(new Country { label = "EG", description = "Egypt" });
countriesList.Add(new Country { label = "EH", description = "Western Sahara" });
countriesList.Add(new Country { label = "ER", description = "Eritrea" });
countriesList.Add(new Country { label = "ES", description = "Spain" });
countriesList.Add(new Country { label = "ET", description = "Ethiopia" });
countriesList.Add(new Country { label = "FI", description = "Finland" });
countriesList.Add(new Country { label = "FJ", description = "Fiji" });
countriesList.Add(new Country { label = "FK", description = "Falkland Islands" });
countriesList.Add(new Country { label = "FM", description = "Micronesia" });
countriesList.Add(new Country { label = "FO", description = "Faroe Islands" });
countriesList.Add(new Country { label = "FR", description = "France" });
countriesList.Add(new Country { label = "GA", description = "Gabon" });
countriesList.Add(new Country { label = "GB", description = "Britain (UK)" });
countriesList.Add(new Country { label = "GD", description = "Grenada" });
countriesList.Add(new Country { label = "GE", description = "Georgia" });
countriesList.Add(new Country { label = "GF", description = "French Guiana" });
countriesList.Add(new Country { label = "GG", description = "Guernsey" });
countriesList.Add(new Country { label = "GH", description = "Ghana" });
countriesList.Add(new Country { label = "GI", description = "Gibraltar" });
countriesList.Add(new Country { label = "GL", description = "Greenland" });
countriesList.Add(new Country { label = "GM", description = "Gambia" });
countriesList.Add(new Country { label = "GN", description = "Guinea" });
countriesList.Add(new Country { label = "GP", description = "Guadeloupe" });
countriesList.Add(new Country { label = "GQ", description = "Equatorial Guinea" });
countriesList.Add(new Country { label = "GR", description = "Greece" });
countriesList.Add(new Country { label = "GS", description = "South Georgia & the South Sandwich Islands" });
countriesList.Add(new Country { label = "GT", description = "Guatemala" });
countriesList.Add(new Country { label = "GU", description = "Guam" });
countriesList.Add(new Country { label = "GW", description = "Guinea-Bissau" });
countriesList.Add(new Country { label = "GY", description = "Guyana" });
countriesList.Add(new Country { label = "HK", description = "Hong Kong" });
countriesList.Add(new Country { label = "HM", description = "Heard Island & McDonald Islands" });
countriesList.Add(new Country { label = "HN", description = "Honduras" });
countriesList.Add(new Country { label = "HR", description = "Croatia" });
countriesList.Add(new Country { label = "HT", description = "Haiti" });
countriesList.Add(new Country { label = "HU", description = "Hungary" });
countriesList.Add(new Country { label = "ID", description = "Indonesia" });
countriesList.Add(new Country { label = "IE", description = "Ireland" });
countriesList.Add(new Country { label = "IL", description = "Israel" });
countriesList.Add(new Country { label = "IM", description = "Isle of Man" });
countriesList.Add(new Country { label = "IN", description = "India" });
countriesList.Add(new Country { label = "IO", description = "British Indian Ocean Territory" });
countriesList.Add(new Country { label = "IQ", description = "Iraq" });
countriesList.Add(new Country { label = "IR", description = "Iran" });
countriesList.Add(new Country { label = "IS", description = "Iceland" });
countriesList.Add(new Country { label = "IT", description = "Italy" });
countriesList.Add(new Country { label = "JE", description = "Jersey" });
countriesList.Add(new Country { label = "JM", description = "Jamaica" });
countriesList.Add(new Country { label = "JO", description = "Jordan" });
countriesList.Add(new Country { label = "JP", description = "Japan" });
countriesList.Add(new Country { label = "KE", description = "Kenya" });
countriesList.Add(new Country { label = "KG", description = "Kyrgyzstan" });
countriesList.Add(new Country { label = "KH", description = "Cambodia" });
countriesList.Add(new Country { label = "KI", description = "Kiribati" });
countriesList.Add(new Country { label = "KM", description = "Comoros" });
countriesList.Add(new Country { label = "KN", description = "St Kitts & Nevis" });
countriesList.Add(new Country { label = "KP", description = "Korea (North)" });
countriesList.Add(new Country { label = "KR", description = "Korea (South)" });
countriesList.Add(new Country { label = "KW", description = "Kuwait" });
countriesList.Add(new Country { label = "KY", description = "Cayman Islands" });
countriesList.Add(new Country { label = "KZ", description = "Kazakhstan" });
countriesList.Add(new Country { label = "LA", description = "Laos" });
countriesList.Add(new Country { label = "LB", description = "Lebanon" });
countriesList.Add(new Country { label = "LC", description = "St Lucia" });
countriesList.Add(new Country { label = "LI", description = "Liechtenstein" });
countriesList.Add(new Country { label = "LK", description = "Sri Lanka" });
countriesList.Add(new Country { label = "LR", description = "Liberia" });
countriesList.Add(new Country { label = "LS", description = "Lesotho" });
countriesList.Add(new Country { label = "LT", description = "Lithuania" });
countriesList.Add(new Country { label = "LU", description = "Luxembourg" });
countriesList.Add(new Country { label = "LV", description = "Latvia" });
countriesList.Add(new Country { label = "LY", description = "Libya" });
countriesList.Add(new Country { label = "MA", description = "Morocco" });
countriesList.Add(new Country { label = "MC", description = "Monaco" });
countriesList.Add(new Country { label = "MD", description = "Moldova" });
countriesList.Add(new Country { label = "ME", description = "Montenegro" });
countriesList.Add(new Country { label = "MF", description = "St Martin (French part)" });
countriesList.Add(new Country { label = "MG", description = "Madagascar" });
countriesList.Add(new Country { label = "MH", description = "Marshall Islands" });
countriesList.Add(new Country { label = "MK", description = "Macedonia" });
countriesList.Add(new Country { label = "ML", description = "Mali" });
countriesList.Add(new Country { label = "MM", description = "Myanmar (Burma)" });
countriesList.Add(new Country { label = "MN", description = "Mongolia" });
countriesList.Add(new Country { label = "MO", description = "Macau" });
countriesList.Add(new Country { label = "MP", description = "Northern Mariana Islands" });
countriesList.Add(new Country { label = "MQ", description = "Martinique" });
countriesList.Add(new Country { label = "MR", description = "Mauritania" });
countriesList.Add(new Country { label = "MS", description = "Montserrat" });
countriesList.Add(new Country { label = "MT", description = "Malta" });
countriesList.Add(new Country { label = "MU", description = "Mauritius" });
countriesList.Add(new Country { label = "MV", description = "Maldives" });
countriesList.Add(new Country { label = "MW", description = "Malawi" });
countriesList.Add(new Country { label = "MX", description = "Mexico" });
countriesList.Add(new Country { label = "MY", description = "Malaysia" });
countriesList.Add(new Country { label = "MZ", description = "Mozambique" });
countriesList.Add(new Country { label = "NA", description = "Namibia" });
countriesList.Add(new Country { label = "NC", description = "New Caledonia" });
countriesList.Add(new Country { label = "NE", description = "Niger" });
countriesList.Add(new Country { label = "NF", description = "Norfolk Island" });
countriesList.Add(new Country { label = "NG", description = "Nigeria" });
countriesList.Add(new Country { label = "NI", description = "Nicaragua" });
countriesList.Add(new Country { label = "NL", description = "Netherlands" });
countriesList.Add(new Country { label = "NO", description = "Norway" });
countriesList.Add(new Country { label = "NP", description = "Nepal" });
countriesList.Add(new Country { label = "NR", description = "Nauru" });
countriesList.Add(new Country { label = "NU", description = "Niue" });
countriesList.Add(new Country { label = "NZ", description = "New Zealand" });
countriesList.Add(new Country { label = "OM", description = "Oman" });
countriesList.Add(new Country { label = "PA", description = "Panama" });
countriesList.Add(new Country { label = "PE", description = "Peru" });
countriesList.Add(new Country { label = "PF", description = "French Polynesia" });
countriesList.Add(new Country { label = "PG", description = "Papua New Guinea" });
countriesList.Add(new Country { label = "PH", description = "Philippines" });
countriesList.Add(new Country { label = "PK", description = "Pakistan" });
countriesList.Add(new Country { label = "PL", description = "Poland" });
countriesList.Add(new Country { label = "PM", description = "St Pierre & Miquelon" });
countriesList.Add(new Country { label = "PN", description = "Pitcairn" });
countriesList.Add(new Country { label = "PR", description = "Puerto Rico" });
countriesList.Add(new Country { label = "PS", description = "Palestine" });
countriesList.Add(new Country { label = "PT", description = "Portugal" });
countriesList.Add(new Country { label = "PW", description = "Palau" });
countriesList.Add(new Country { label = "PY", description = "Paraguay" });
countriesList.Add(new Country { label = "QA", description = "Qatar" });
countriesList.Add(new Country { label = "RE", description = "Reunion" });
countriesList.Add(new Country { label = "RO", description = "Romania" });
countriesList.Add(new Country { label = "RS", description = "Serbia" });
countriesList.Add(new Country { label = "RU", description = "Russia" });
countriesList.Add(new Country { label = "RW", description = "Rwanda" });
countriesList.Add(new Country { label = "SA", description = "Saudi Arabia" });
countriesList.Add(new Country { label = "SB", description = "Solomon Islands" });
countriesList.Add(new Country { label = "SC", description = "Seychelles" });
countriesList.Add(new Country { label = "SD", description = "Sudan" });
countriesList.Add(new Country { label = "SE", description = "Sweden" });
countriesList.Add(new Country { label = "SG", description = "Singapore" });
countriesList.Add(new Country { label = "SH", description = "St Helena" });
countriesList.Add(new Country { label = "SI", description = "Slovenia" });
countriesList.Add(new Country { label = "SJ", description = "Svalbard & Jan Mayen" });
countriesList.Add(new Country { label = "SK", description = "Slovakia" });
countriesList.Add(new Country { label = "SL", description = "Sierra Leone" });
countriesList.Add(new Country { label = "SM", description = "San Marino" });
countriesList.Add(new Country { label = "SN", description = "Senegal" });
countriesList.Add(new Country { label = "SO", description = "Somalia" });
countriesList.Add(new Country { label = "SR", description = "Suriname" });
countriesList.Add(new Country { label = "SS", description = "South Sudan" });
countriesList.Add(new Country { label = "ST", description = "Sao Tome & Principe" });
countriesList.Add(new Country { label = "SV", description = "El Salvador" });
countriesList.Add(new Country { label = "SX", description = "St Maarten (Dutch part)" });
countriesList.Add(new Country { label = "SY", description = "Syria" });
countriesList.Add(new Country { label = "SZ", description = "Swaziland" });
countriesList.Add(new Country { label = "TC", description = "Turks & Caicos Is" });
countriesList.Add(new Country { label = "TD", description = "Chad" });
countriesList.Add(new Country { label = "TF", description = "French Southern & Antarctic Lands" });
countriesList.Add(new Country { label = "TG", description = "Togo" });
countriesList.Add(new Country { label = "TH", description = "Thailand" });
countriesList.Add(new Country { label = "TJ", description = "Tajikistan" });
countriesList.Add(new Country { label = "TK", description = "Tokelau" });
countriesList.Add(new Country { label = "TL", description = "East Timor" });
countriesList.Add(new Country { label = "TM", description = "Turkmenistan" });
countriesList.Add(new Country { label = "TN", description = "Tunisia" });
countriesList.Add(new Country { label = "TO", description = "Tonga" });
countriesList.Add(new Country { label = "TR", description = "Turkey" });
countriesList.Add(new Country { label = "TT", description = "Trinidad & Tobago" });
countriesList.Add(new Country { label = "TV", description = "Tuvalu" });
countriesList.Add(new Country { label = "TW", description = "Taiwan" });
countriesList.Add(new Country { label = "TZ", description = "Tanzania" });
countriesList.Add(new Country { label = "UA", description = "Ukraine" });
countriesList.Add(new Country { label = "UG", description = "Uganda" });
countriesList.Add(new Country { label = "UM", description = "US minor outlying islands" });
countriesList.Add(new Country { label = "US", description = "United States" });
countriesList.Add(new Country { label = "UY", description = "Uruguay" });
countriesList.Add(new Country { label = "UZ", description = "Uzbekistan" });
countriesList.Add(new Country { label = "VA", description = "Vatican City" });
countriesList.Add(new Country { label = "VC", description = "St Vincent" });
countriesList.Add(new Country { label = "VE", description = "Venezuela" });
countriesList.Add(new Country { label = "VG", description = "Virgin Islands (UK)" });
countriesList.Add(new Country { label = "VI", description = "Virgin Islands (US)" });
countriesList.Add(new Country { label = "VN", description = "Vietnam" });
countriesList.Add(new Country { label = "VU", description = "Vanuatu" });
countriesList.Add(new Country { label = "WF", description = "Wallis & Futuna" });
countriesList.Add(new Country { label = "WS", description = "Samoa (western)" });
countriesList.Add(new Country { label = "YE", description = "Yemen" });
countriesList.Add(new Country { label = "YT", description = "Mayotte" });
countriesList.Add(new Country { label = "ZA", description = "South Africa" });
countriesList.Add(new Country { label = "ZM", description = "Zambia" });
countriesList.Add(new Country { label = "ZW", description = "Zimbabwe" });
